
<html>
    <div id="view-content">
        <div  class="container" align="center">
            
            <title>Place Order</title>
            <?php 
            
$this->headScript()->appendFile($this->baseUrl('/assets/js/placeOrder.js'));
//$this->headScript()->offsetSetFile(1, $this->baseUrl('/assets/js/placeOrder.js'));
?>
            <?php 
            if ($this->form) {
                ?>
                <br/>
                <table class="table table-striped" width=80%>
                    <thead>
                        <tr>
                            <th>Check</th>
                            <th>Product Description</th>
                            <th>Product Price</th>
                            <th>Product Quantity</th>
                            <th>Product Discount</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php for ($i=0;$i<count($this->form->checkBoxArray);$i++) 
                        { ?>
                            <tr>
                                <td><?php echo $this->form->checkBoxArray[$i]; ?></td>
                                <td><?php echo $this->form->productArray[$i]; ?></td>
                                <td><?php echo $this->form->priceArray[$i]; ?></td>
                                <td><?php echo $this->form->quantityArray[$i]; ?></td>
                                <td><?php echo $this->form->discountArray[$i]; ?></td>

                            </tr>
                        <?php } ?>
                    </tbody>
                </table>
            <?php } else {
                ?>
                <p>There is no product to Display</p>
                <?php
            }
            ?>

        </div>
    </div> <!-- outer div -->
    
</html>
