<?php echo $this->doctype(); ?>


<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="icon" href="../../favicon.ico">


        <link href="<?php echo $this->baseUrl('/bootstrap/css/bootstrap.min.css'); ?>" rel="stylesheet">

        <link href="<?php echo $this->baseUrl('/bootstrap/css/dashboard.css'); ?>" rel="stylesheet">


        <script src="<?php echo $this->baseUrl('/bootstrap/js/ie-emulation-modes-warning.js'); ?>"></script>
    </head>

    <body>

        <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">Ready2Serve</a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="#">Settings</a></li>
                        <li><a href="#">About Us</a></li>
                        <li><a href="#">Help</a></li>
                    </ul>
                    <form class="navbar-form navbar-right">
                        <input type="text" class="form-control" placeholder="Search...">
                    </form>
                </div>
            </div>
        </div>
        <!--class="col-md-2"-->
        <div class="col-md-2" >
            <?php
            if (Zend_Controller_Front::getInstance()->getRequest()
                            ->getControllerName() != 'Auth' &&
                            Zend_Controller_Front::getInstance()->getRequest()
                            ->getControllerName() != 'auth') {
                if (Zend_Auth::getInstance()->hasIdentity()) {
                    if (Zend_Auth::getInstance()->getIdentity()
                            ->person_type == 'Admin') {
                        echo $this->render('sidebar_admin.phtml');
                    } else if (Zend_Auth::getInstance()
                                    ->getIdentity()->person_type == 'Salesperson') {
                        echo $this->render('sidebar_salesperson.phtml');
                    }
                }
            }
            ?>
        </div>
        
        <script src="<?php echo $this->baseUrl('jquery.min.js'); ?>"></script>
        <script src="<?php echo $this->baseUrl('/bootstrap/js/jquery.js'); ?>"></script>
        <script src="<?php echo $this->baseUrl('/bootstrap/js/bootstrap.min.js'); ?>"></script>
        <script src="<?php echo $this->baseUrl('/bootstrap/js/docs.min.js'); ?>"></script>
        <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
        <script src="<?php echo $this->baseUrl('/bootstrap/js/ie10-viewport-bug-workaround.js'); ?>"></script>

        <div id="content" class="col-md-8" >
            <?php
            echo $this->layout()->content;
            ?>
        </div>

    </body>
</html>
