<div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li class="active"><a href="/auth/login">View Orders</a></li>
            <li><a href="/person/edit-account-info">Edit Account Info</a></li>
            <li><a href="">Add Product</a></li>
            <li><a href="">Update/Edit Product</a></li>
            <li><a href="/product/show-all-products">Show All Product</a></li>
            <li><a href="#">Delete Product</a></li>
            <li><a href="/auth/logout">Logout</a></li>
        </div>
       
      </div>
    </div>