
<br /><br />
<div id="view-content">
<div  class="container">
    <title>Add Items in Deal</title>
    <?php $this->headScript()->appendFile(
                    $this->baseUrl('/assets/js/placeOrder.js'));?>
    <form role="form" method="post">
        
    <table class="table" id="t1" name="t1" style="width:70%" align="center">
        <thead>
                <tr>
                    <th>Check to Select</th>
                    <th>Product Name</th>
                    <th>Quantity</th>
                </tr>
              </thead>
              
               <tbody>
        <?php foreach ($this->list as $key => $val): ?>
            <tr>
                <td><?php echo $this->form->getElement($val['product_id']) ?></td>
                <td><?php echo $this->escape($val['product_description']) ?></td>
                <td><?php echo $this->form->getElement($val['product_id'].'q') ?></td>
            </tr>
        <?php endforeach; ?>
            </tbody>
    </table>
        <div align="center">
    <?php
    echo $this->form->getElement('Confirm');
    ?>
            </div>

 </form>
</div>
</div>
