
<br /><br />
<div id="view-content">
<div  class="container" align="center">
    <form role="form" method="post">
        
    <table class="table" id="t1" name="t1" style="width:80%">
        <thead>
                <tr>
                   <th>Product ID</th>
                    <th>Product Name</th>
                    <th>Product Type</th>
                    <th>Unit Price</th>
                    <th>Product Availability</th>
                    <th>Delete Product</th>
                </tr>
              </thead>
              
               <tbody>
        <?php foreach ($this->list as $key => $val): ?>
            <tr>
                <td><?php echo $this->escape($val['product_id']) ?></td>
                <td><?php echo $this->escape(trim($val['product_description'])) ?></td>
                <td><?php echo $this->escape(trim($val['product_type'])) ?></td>
                <td><?php echo $this->escape(trim($val['product_price'])) ?></td>
                <td><?php echo $this->escape(trim($val['is_product_available'])) ?></td>
                <td><?php echo $this->form->getElement(trim($val['product_id'])) ?></td>
            </tr>
        <?php endforeach; ?>
            </tbody>
    </table>
    <?php
    echo $this->form->getElement('Confirm');
    ?>
        

 </form>
</div>
</div>

<script src="<?php echo $this->baseUrl('/bootstrap/js/colResizable-1.3.min.js'); ?>"></script>
<script type="text/javascript">
    
    $("#t1").colResizable();
    
</script>