<br /><br />
<div id="view-content">
<div  class="container" align="center">
    <?php
    ?>
    <table class="table table-striped">
        <thead>
                <tr>
                   <th>Product ID</th>
                    <th>Product Name</th>
                    <th>Product Type</th>
                    <th>Unit Price</th>
                    <th>Delete Product</th>
                </tr>
              </thead>
              
               <tbody>
        <?php foreach ($this->list as $key => $val): ?>
            <tr>
                <td><?php echo $this->escape($val['product_id']); ?></td>
                <td><?php echo $this->escape($val['product_description']); ?></td>
                <td><?php echo $this->escape($val['product_type']); ?></td>
                <td><?php echo $this->escape($val['product_price']); ?></td>
                 <td><?php echo $this->form->getElement($val['product_id']); ?></td>
            </tr>
        <?php endforeach; ?>
            </tbody>
    </table>
    <?php
    //echo $this->formRow($this->form->getElement('submit'));
    //echo $this->form()->closeTag();
    ?>
</div>
</div>