<html>
    <div id="view-content">
        <div  class="container" align="center">
            <?php
            if ($this->result) {
                ?>
                <table class="table table-striped" cellpadding="8">
                    <thead>
                        <tr>
                            <th>Product Description</th>
                            <th>Product Type</th>
                            <th>Product Price</th>
                            <th>Product Availability</th>
                            <th>Product Orderability</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->result as $prod) { ?>
                            <tr>
                                <td><?php echo $prod['product_description']; ?></td>
                                <td><?php echo $prod['product_type']; ?></td>
                                <td><?php echo $prod['product_price']; ?></td>
                                <td><?php echo $prod['is_product_available']; ?></td>
                                <td><?php echo $prod['is_product_oderable']; ?></td>

                            </tr>
                        <?php } ?>
                    </tbody>
                </table>
            <?php } else {
                ?>
                <p>There is no product to Display</p>
                <?php
            }
            ?>

        </div>
    </div> <!-- outer div -->
</html>

