<style>
    a:link,
    a:visited
    {
        color: #0398CA;
    }

    span#zf-name
    {
        color: #91BE3F;
    }

    div#welcome
    {
        color: #FFFFFF;
        background-image: url(http://framework.zend.com/images/bkg_header.jpg);
        width:  600px;
        height: 400px;
        border: 2px solid #444444;
        overflow: hidden;
        text-align: center;
    }

    div#more-information
    {
        background-image: url(http://framework.zend.com/images/bkg_body-bottom.gif);
        height: 100%;
    }
</style>
<div id="welcome">
    <h1>Welcome to <span id="zf-name">Ready To Serve -POS</span></h1>

    <h3>You are landed on Index page</h3>

    <div id="more-information">
        <a href="/auth/login" ><input type="button" class="btn btn-primary" style="width: 100px" value="Sign In"></a>
    </div>
</div>